### ISSUE TITLE
About icenReg

### ISSUE THREAD

**Issue by nursenaaksunger** [pistacliffcho/icenReg_devel#10]
Dear Clifford,

Sorry for creating issue via Github but I could not reach you via mentioned e-mail. I have a question related to icenReg command. I’m using your command for semi-parametric Cox model. I have data on recurrent ordered failures and I’m wondering how can I specify recurrent data stucture in icenReg command. I want to use PWP-Total time model with icenReg is that possible? 

Best regards,
Nursena

**Comment by pistacliffcho** [comment]
Hi Nursena, 

Unfortunately icenReg does not support a recurrent data structure. 

Best, 
Cliff
